In [7]:
import pandas as pd

In [22]:
import numpy as np

In [5]:
a = np.array([2,3,4,5,6])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.size

5

In [9]:
a.dtype

dtype('int32')

In [10]:
a[:-1]

array([2, 3, 4, 5])

In [8]:
a.shape

(5,)

In [12]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [13]:
a= [[11,12,13],[21,22,23],[31,32,33]]
arr = np.array(a)

In [14]:
arr

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [15]:
arr.ndim

2

In [16]:
arr.shape

(3, 3)

In [17]:
arr.size

9

In [23]:
arr[1,1]

22

In [24]:
arr[0:2,1:]

array([[12, 13],
       [22, 23]])

In [25]:
a=np.array([-1,1])
b=np.array([1,1])

In [31]:
np.dot(a,b)

0

In [28]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)

In [30]:
Z

array([[2, 2],
       [2, 2]])

In [22]:
arr[1:,1:]

array([[22, 23],
       [32, 33]])

In [34]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.offline import plot
import matplotlib.pyplot as plt
import datetime
from pycoingecko import CoinGeckoAPI
from mplfinance.original_flavor import candlestick2_ohlc

ModuleNotFoundError: No module named 'mplfinance'

In [35]:
from pycoingecko import CoinGeckoAPI

In [36]:
cg = CoinGeckoAPI()

bitcoin_data = cg.get_coin_market_chart_by_id(id='bitcoin', vs_currency='usd',days=30)

In [40]:
bitcoin_price_data = bitcoin_data['prices']

bitcoin_price_data[0:5]

[[1670248909666, 17269.310501635624],
 [1670252462430, 17219.590861680957],
 [1670256055457, 17095.134772010668],
 [1670259704174, 17056.581550243616],
 [1670263331517, 17076.030889043755]]

In [41]:
data = pd.DataFrame(bitcoin_price_data, columns=['TimeStamp', 'Price'])

In [42]:
data.head()

TimeStamp         Price
0  1670248909666  17269.310502
1  1670252462430  17219.590862
2  1670256055457  17095.134772
3  1670259704174  17056.581550
4  1670263331517  17076.030889

In [50]:
var = "01234567"
print(var[::2])

0246


In [51]:
x=2/2

In [52]:
x

1.0

In [53]:
'1,2,3,4'.split(',') 

['1', '2', '3', '4']

In [58]:
for i in range(1,5):
    if(i!=1):
        print(i)

2
3
4


In [60]:
import requests
import html5lib
import bs4